version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - './.dbdata/db:/var/lib/mysql'
    restart: always
    ports:
      - '3310:3306' # TODO: Cambiar para cada proyecto
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    ports:
      - '8084:80' # TODO: Cambiar para cada proyecto
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3310
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      VIRTUAL_HOST: ${DOMAINS}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - '8184:80' # TODO: Cambiar para cada proyecto
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
